# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\coding\python\homework\Online-question-bank-platform\ui\ChooseLoadFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chooseLoadFile(object):
    def setupUi(self, chooseLoadFile):
        chooseLoadFile.setObjectName("chooseLoadFile")
        chooseLoadFile.resize(400, 146)
        chooseLoadFile.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(chooseLoadFile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(chooseLoadFile)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit = MyQTextEdit(chooseLoadFile)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setMarkdown("")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.choose = QtWidgets.QCommandLinkButton(chooseLoadFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose.sizePolicy().hasHeightForWidth())
        self.choose.setSizePolicy(sizePolicy)
        self.choose.setMaximumSize(QtCore.QSize(30, 40))
        self.choose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.choose.setIcon(icon)
        self.choose.setObjectName("choose")
        self.horizontalLayout.addWidget(self.choose, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(chooseLoadFile)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(chooseLoadFile)
        self.buttonBox.rejected.connect(chooseLoadFile.reject)
        self.buttonBox.accepted.connect(chooseLoadFile.accept)
        QtCore.QMetaObject.connectSlotsByName(chooseLoadFile)

    def retranslateUi(self, chooseLoadFile):
        _translate = QtCore.QCoreApplication.translate
        chooseLoadFile.setWindowTitle(_translate("chooseLoadFile", "Dialog"))
        self.label.setText(_translate("chooseLoadFile", "文件地址"))
        self.textEdit.setHtml(_translate("chooseLoadFile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("chooseLoadFile", "输入文件地址或拖入此处"))
from ui.MyWidgets.MyQTextEdit import MyQTextEdit
