# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.questionList = QtWidgets.QListWidget(self.centralwidget)
        self.questionList.setObjectName("questionList")
        item = QtWidgets.QListWidgetItem()
        self.questionList.addItem(item)
        self.gridLayout.addWidget(self.questionList, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 424, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setEnabled(True)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.addQuestionButton = QtWidgets.QAction(MainWindow)
        self.addQuestionButton.setCheckable(False)
        self.addQuestionButton.setObjectName("addQuestionButton")
        self.selfTestButton = QtWidgets.QAction(MainWindow)
        self.selfTestButton.setObjectName("selfTestButton")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.menu.addAction(self.addQuestionButton)
        self.menu.addAction(self.selfTestButton)
        self.menu.addAction(self.actionclose)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.questionList.isSortingEnabled()
        self.questionList.setSortingEnabled(False)
        item = self.questionList.item(0)
        item.setText(_translate("MainWindow", "aa"))
        self.questionList.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.addQuestionButton.setText(_translate("MainWindow", "新题上传"))
        self.selfTestButton.setText(_translate("MainWindow", "自测"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.actionclose.triggered.connect(lambda :self.closeSys(MainWindow))

    def closeSys(self,MainWindow):
        MainWindow.close()
