# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\coding\python\homework\Online-question-bank-platform\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.questionCategory = QtWidgets.QWidget()
        self.questionCategory.setGeometry(QtCore.QRect(0, 0, 754, 503))
        self.questionCategory.setObjectName("questionCategory")
        self.questionCategoryLayout = QtWidgets.QVBoxLayout(self.questionCategory)
        self.questionCategoryLayout.setObjectName("questionCategoryLayout")
        self.scrollArea.setWidget(self.questionCategory)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.questionDetail = MyQuestionInfo(self.page1)
        self.questionDetail.setObjectName("questionDetail")
        self.gridLayout_3.addWidget(self.questionDetail, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setEnabled(True)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.addQuestionButton = QtWidgets.QAction(MainWindow)
        self.addQuestionButton.setCheckable(False)
        self.addQuestionButton.setObjectName("addQuestionButton")
        self.selfTestButton = QtWidgets.QAction(MainWindow)
        self.selfTestButton.setObjectName("selfTestButton")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.registerButton = QtWidgets.QAction(MainWindow)
        self.registerButton.setObjectName("registerButton")
        self.loginButton = QtWidgets.QAction(MainWindow)
        self.loginButton.setObjectName("loginButton")
        self.logoutButton = QtWidgets.QAction(MainWindow)
        self.logoutButton.setObjectName("logoutButton")
        self.menu.addAction(self.addQuestionButton)
        self.menu.addAction(self.selfTestButton)
        self.menu.addAction(self.actionclose)
        self.menu_2.addAction(self.registerButton)
        self.menu_2.addAction(self.loginButton)
        self.menu_2.addAction(self.logoutButton)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "我的"))
        self.addQuestionButton.setText(_translate("MainWindow", "新题上传"))
        self.selfTestButton.setText(_translate("MainWindow", "自测"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.registerButton.setText(_translate("MainWindow", "注册"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
        self.logoutButton.setText(_translate("MainWindow", "退出登录"))
from ui.MyWidgets.MyQuestionInfo import MyQuestionInfo
